languageCode: en-us

title: Hugo demo

publishDir: "_site"

module:
  mounts:
    # > When you add a mount, the default mount for the concerned target root is ignored: be sure to explicitly add it.
    # - https://gohugo.io/hugo-modules/configuration/#module-config-mounts
    - source: "assets"
      target: "assets"
    - source: "static"
      target: "static"

    # Make USWDS files available as assets (so they can be fingerprinted etc.), but also as static files
    # (so we can ensure that anything referenced via `url()` in USWDS's CSS can still be found.)
    - source: "node_modules/@uswds/uswds/dist"
      target: "assets/@uswds"
    - source: "node_modules/@uswds/uswds/dist/fonts"
      target: "static/@uswds/fonts"
    - source: "node_modules/@uswds/uswds/dist/img"
      target: "static/@uswds/img"

# BEGIN Workaround to get Hugo working with asdf
# See: https://github.com/gohugoio/hugo/issues/9811
security:
  exec:
    osEnv:
      - "(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$"
      - ^ASDF_DIR$
      - ^HOME$
# END asdf workaround
