baseURL: http://example.org/
languageCode: en-us
title: Hugo demo

module:
  mounts:
    # > When you add a mount, the default mount for the concerned target root is ignored: be sure to explicitly add it.
    # - https://gohugo.io/hugo-modules/configuration/#module-config-mounts
    - source: "assets"
      target: "assets"
    - source: "static"
      target: "static"

    - source: "node_modules/@uswds/uswds/dist"
      target: "assets/@uswds"
    - source: "node_modules/@uswds/uswds/dist"
      target: "static/@uswds"

# BEGIN Workaround to get Hugo working with asdf
# See: https://github.com/gohugoio/hugo/issues/9811
security:
  exec:
    osEnv:
      - "(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$"
      - ^ASDF_DIR$
      - ^HOME$
# END asdf workaround
